### ISSUE TITLE
Not available on crates.io?

### ISSUE THREAD

**Issue by pevdh** [SpiralP/rust-ieee80211#2]
"ieee80211" does not seem to exist on crates.io. Am I not looking in the right place?

Cargo.lock:

```
[dependencies]
ieee80211 = "0.1.0"
```

**Comment by SpiralP** [comment]
yeah, I don't think I put it on on crates, you can use it with `cargo add https://github.com/SpiralP/rust-ieee80211.git` tho!

**Comment by SpiralP** [comment]
or via
```

[dependencies]
ieee80211 = { git = "https://github.com/SpiralP/rust-ieee80211.git" }
```

**Comment by pevdh** [comment]
Thanks! Just out of curiosity - is there a reason haven't published on crates.io? Would it incur a lot of maintenance?
